apiVersion: v1
kind: ConfigMap

metadata:
  name: app-config
  namespace: {{ .Values.namespace.backend }}

data:
  AUTH_SERVICE: "http://auth-service"
  USER_SERVICE: "http://user-service"
  PRODUCT_SERVICE: "http://product-service"
  INVENTORY_SERVICE: "http://inventory-service"
  CART_SERVICE: "http://cart-service"
  ORDER_SERVICE: "http://order-service"
  PAYMENT_SERVICE: "http://payment-service"
  DELIVERY_SERVICE: "http://delivery-service"
  NOTIFICATION_SERVICE: "http://notification-service"
  SUPPORT_SERVICE: "http://support-service"

  REDIS_HOST: "redis"

  RABBITMQ_HOST: "rabbitmq"

  DATABASE_URL: "postgresql://commerce:commerce@postgres:5432/commerce_db"

  ENV: "development"