apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc
  namespace: {{ $.Release.Namespace }}

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.postgres.storage }}

  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: redis-pvc
  namespace: {{ $.Release.Namespace }}

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.redis.storage }}

  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: rabbitmq-pvc
  namespace: {{ $.Release.Namespace }}

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.rabbitmq.storage }}

  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: grafana-pvc
  namespace: {{ $.Release.Namespace }}

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.grafana.storage }}

  storageClassName: standard

---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: prometheus-pvc
  namespace: {{ $.Release.Namespace }}

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.prometheus.storage }}

  storageClassName: standard