apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              value: postgresql://commerce:commerce@postgres:5432/commerce_db

            - name: REDIS_HOST
              value: redis

            - name: RABBITMQ_HOST
              value: rabbitmq

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30006