apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config

data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:

      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway:8000']

      - job_name: 'auth-service'
        static_configs:
          - targets: ['auth-service:8000']

      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:8000']

      - job_name: 'product-service'
        static_configs:
          - targets: ['product-service:8000']

      - job_name: 'cart-service'
        static_configs:
          - targets: ['cart-service:8000']

      - job_name: 'order-service'
        static_configs:
          - targets: ['order-service:8000']

      - job_name: 'payment-service'
        static_configs:
          - targets: ['payment-service:8000']

      - job_name: 'delivery-service'
        static_configs:
          - targets: ['delivery-service:8000']

      - job_name: 'notification-service'
        static_configs:
          - targets: ['notification-service:8000']

      - job_name: 'inventory-service'
        static_configs:
          - targets: ['inventory-service:8000']

      - job_name: 'support-service'
        static_configs:
          - targets: ['support-service:8000']

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090']