apiVersion: apps/v1
kind: Deployment

metadata:
  name: prometheus

spec:
  replicas: 1

  selector:
    matchLabels:
      app: prometheus

  template:
    metadata:
      labels:
        app: prometheus

    spec:
      containers:
        - name: prometheus

          image: prom/prometheus

          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"

          ports:
            - containerPort: 9090

          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"

            limits:
              cpu: "400m"
              memory: "768Mi"

          volumeMounts:
            - name: config
              mountPath: /etc/prometheus

            - name: prometheus-storage
              mountPath: /prometheus

      volumes:
        - name: config
          configMap:
            name: prometheus-config

        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc