name: CD Production Pipeline

on:
  push:
    branches:
      - release

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      #PYTHON
   
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


 
      - name: Build API Gateway
        run: docker build -t api-gateway:prod -f ./services/api_gateway/Dockerfile .

      - name: Build Auth Service
        run: docker build -t auth-service:prod -f ./services/auth_service/Dockerfile .

      - name: Build User Service
        run: docker build -t user-service:prod -f ./services/user_service/Dockerfile .

      - name: Build Product Service
        run: docker build -t product-service:prod -f ./services/product_service/Dockerfile .

      - name: Build Inventory Service
        run: docker build -t inventory-service:prod -f ./services/inventory_service/Dockerfile .

      - name: Build Cart Service
        run: docker build -t cart-service:prod -f ./services/cart_service/Dockerfile .

      - name: Build Order Service
        run: docker build -t order-service:prod -f ./services/order_service/Dockerfile .

      - name: Build Payment Service
        run: docker build -t payment-service:prod -f ./services/payment_service/Dockerfile .

      - name: Build Delivery Service
        run: docker build -t delivery-service:prod -f ./services/delivery_service/Dockerfile .

      - name: Build Notification Service
        run: docker build -t notification-service:prod -f ./services/notification_service/Dockerfile .

      - name: Build Support Service
        run: docker build -t support-service:prod -f ./services/support_service/Dockerfile .


 
      - name: Production Build Success
        run: |
          echo "Production pipeline completed successfully"